name: buf-pull-request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.67.0"
          buf_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}

      - uses: bufbuild/buf-lint-action@v1

      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://buf.build/smartevp8/api"
